OnlineShop/OnlineShopWebApp/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;

namespace OnlineShopWebApp.Models
{
    public class OrderViewModel
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public List<CartItemViewModel> CartItems { get; set; }
        public UserDeliveryInfoViewModel UserInfo { get; set; }
        public OrderStatusViewModel Status { get; set; }
        public DateTime CreateTime { get; set; }

        public OrderViewModel()
        {
            Status = OrderStatusViewModel.Created;
            CreateTime = DateTime.Now;
        }
    }
}

OnlineShop/OnlineShopWebApp/Areas/Admin/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Areas.Admin.Controllers
{
    [Area(Constants.AdminRoleName)]
    [Authorize(Roles = Constants.AdminRoleName)]
    public class OrderController : Controller
    {
        private readonly IMapper mapper;
        private readonly IOrdersRepository ordersRepository;
        public OrderController(IMapper mapper, IOrdersRepository ordersRepository)
        {
            this.mapper = mapper;
            this.ordersRepository = ordersRepository;
        }
        public async Task<ActionResult> OrderDetails(string orderId)
        {
            var order = await ordersRepository.TryGetByIdAsync(orderId);
            var orderViewModel = mapper.Map<OrderViewModel>(order);
            return View(orderViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> OrderDetails(string orderId, OrderStatusViewModel status)
        {
            var order = await ordersRepository.TryGetByIdAsync(orderId);
            await ordersRepository.UpdateOrderStatusAsync(orderId, (OrderStatus)(int)status);
            var orderViewModel = mapper.Map<OrderViewModel>(order);
            return View(orderViewModel);
        }
        public async Task<ActionResult> Orders()
        {
            var orders = await ordersRepository.GetAllAsync();
            var ordersViewModels = mapper.Map<List<OrderViewModel>>(orders);
            return View(ordersViewModels);
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/CatalogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShopWebApp.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IMapper mapper;
        private readonly IProductsRepository productsRepository;
        private readonly IWishListsRepository wishListsRepository;
        public CatalogController(IMapper mapper, IProductsRepository productsRepository, IWishListsRepository wishListsRepository)
        {
            this.mapper = mapper;
            this.productsRepository = productsRepository;
            this.wishListsRepository = wishListsRepository;
        }
        public async Task<ActionResult> Index()
        {
            var products = await productsRepository.GetAllAsync();
            await wishListsRepository.IsWishAsync(products, Constants.UserId);
            var productsViewModels = mapper.Map<List<ProductViewModel>>(products);
            return View(productsViewModels);
        }

        [HttpPost]
        public async Task<ActionResult> Search(string request)
        {
            if(request == null) { return RedirectToAction("Index"); }
            var products = await productsRepository.SearchAsync(request);
            if (products == null || products.Count == 0)
                return View("NotFound");
            var productsViewModels = mapper.Map<List<ProductViewModel>>(products);
            return View("Index", productsViewModels);
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Models;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private DatabaseContext databaseContext;
        private readonly IMapper mapper;
        private readonly ICartsRepository cartsRepository;
        private readonly IOrdersRepository ordersRepository;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly string userId;
        public OrderController(DatabaseContext databaseContext, IMapper mapper, ICartsRepository cartsRepository, IOrdersRepository ordersRepository, IHttpContextAccessor httpContextAccessor)
        {
            this.databaseContext = databaseContext; 
            this.mapper = mapper;
            this.cartsRepository = cartsRepository;
            this.ordersRepository = ordersRepository;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
        public IActionResult OrderRegistration()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> OrderRegistration(UserDeliveryInfoViewModel user)
        {
            if (ModelState.IsValid)
            {
                var cart = await cartsRepository.TryGetCartAsync(userId);
                if (cart != null)
                {
                    var order = new Order
                    {
                        UserId = userId,
                        UserInfo = mapper.Map<UserDeliveryInfo>(user),
                        CartItems = cart.Items,
                    };
                    var price = 0;
                    foreach (var item in cart.Items)
                    {
                        price += item.Product.Cost * item.Count;
                    }
                    var promo = await databaseContext.Promocodes.FirstOrDefaultAsync(x => x.Text == user.PromocodeText);
                    if (promo != null) 
                        price = price - (price * promo.Discount / 100);
                    order.FullPrice = price;
                    await ordersRepository.SaveOrderAsync(order);
                    await cartsRepository.RemoveCartAsync(cart);
                }
                return View("Done");
            }
            return View();
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Order/Done.cshtml
Готово! Ваш заказ успешно оформлен!<br>
<a class="btn" asp-area="" asp-controller="Catalog" asp-action="Index" style="background-color:#74992e" role="button">Продолжить покупки</a>

OnlineShop/OnlineShopWebApp/Views/Order/OrderRegistration.cshtml
@model UserDeliveryInfoViewModel

<div class="text-center">
    <h1 class="display-4">Оформление заказа</h1>
</div>
<form method="post">
    <div>
        <fieldset>
            <legend>Анкета оформоления заказа</legend>

            <div>
                <label asp-for="Name">Имя заказчика</label><br>
                <input type="text" asp-for="Name" placeholder="Пётр"><br>
                <span asp-validation-for="Name" style="color:red"></span>
            </div>

            <div>
                <label asp-for="Tel">Телефон</label><br>
                <input type="tel" asp-for="Tel" placeholder="89771234567"><br>
                <span asp-validation-for="Tel" style="color:red"></span>
            </div>

            <div>
                <label asp-for="Address">Адрес доставки</label><br>
                <input type="text" asp-for="Address" placeholder="Город, улица, дом, квартира"><br>
                <span asp-validation-for="Address" style="color:red"></span>
            </div>

            <div>
                <label asp-for="Email">Email</label><br>
                <input type="email" asp-for="Email"><br>
                <span asp-validation-for="Email" style="color:red"></span>
            </div>

            <div>
                <label asp-for="PromocodeText">Промокод (необязательно)</label><br>
                <input type="text" asp-for="PromocodeText"><br>
                <span asp-validation-for="PromocodeText" style="color:red"></span>
            </div>

            <button type="submit" class="btn" style="background-color:green" asp-area="" asp-controller="Order" asp-action="OrderRegistration">Оформить заказ</button>
        </fieldset>
    </div>
</form>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}