OnlineShop/OnlineShopWebApp/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Models;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private DatabaseContext databaseContext;
        private readonly IMapper mapper;
        private readonly ICartsRepository cartsRepository;
        private readonly IOrdersRepository ordersRepository;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly string userId;
        public OrderController(DatabaseContext databaseContext, IMapper mapper, ICartsRepository cartsRepository, IOrdersRepository ordersRepository, IHttpContextAccessor httpContextAccessor)
        {
            this.databaseContext = databaseContext; 
            this.mapper = mapper;
            this.cartsRepository = cartsRepository;
            this.ordersRepository = ordersRepository;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
        public IActionResult OrderRegistration()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> OrderRegistration(UserDeliveryInfoViewModel user)
        {
            if (ModelState.IsValid)
            {
                var cart = await cartsRepository.TryGetCartAsync(userId);
                if (cart != null)
                {
                    var order = new Order
                    {
                        UserId = userId,
                        UserInfo = mapper.Map<UserDeliveryInfo>(user),
                        CartItems = cart.Items,
                    };
                    var price = 0;
                    foreach (var item in cart.Items)
                    {
                        price += item.Product.Cost * item.Count;
                    }
                    var promo = await databaseContext.Promocodes.FirstOrDefaultAsync(x => x.Text == user.PromocodeText);
                    if (promo != null) 
                        price = price - (price * promo.Discount / 100);
                    order.FullPrice = price;
                    await ordersRepository.SaveOrderAsync(order);
                    await cartsRepository.RemoveCartAsync(cart);
                }
                return View("Done");
            }
            return View();
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Cart/CartViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.Models;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.Cart
{
    public class CartViewComponent : ViewComponent
    {
        private readonly IMapper mapper;
        private readonly ICartsRepository cartsRepository;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly string userId;
        public CartViewComponent(IMapper mapper, ICartsRepository cartsRepository, IHttpContextAccessor httpContextAccessor)
        {
            this.mapper = mapper;
            this.cartsRepository = cartsRepository;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                var cookies = httpContextAccessor.HttpContext.Request.Cookies;
                if (cookies.ContainsKey("CurrentUserId"))
                {
                    userId = cookies["CurrentUserId"];
                }
                else
                {
                    userId = Guid.NewGuid().ToString();
                    httpContextAccessor.HttpContext.Response.Cookies.Append("CurrentUserId", userId);
                }
            }
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = await cartsRepository.TryGetCartAsync(userId);
            var cartViewModel = mapper.Map<CartViewModel>(cart);           
            return View("Cart", cartViewModel);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/User/UserViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using System;

namespace OnlineShopWebApp.Views.Shared.Components.User
{
    public class UserViewComponent : ViewComponent
    {
        private readonly UserManager<OnlineShop.Db.Models.User> userManager;
        public UserViewComponent(UserManager<OnlineShop.Db.Models.User> userManager)
        {
            this.userManager = userManager;
        }
        public IViewComponentResult Invoke(string claimId)
        {
            var id = claimId.Remove(0, claimId.Length-36);
            var user = userManager.FindByIdAsync(id).Result;
            return View("User", user);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShopWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/Логотип.png" width="45" height="45" align="middle"/>  ToPetsWithLove&#128420;</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Каталог</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("Cart")
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="WishList" asp-action="Index">Избранное</a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                            @await Component.InvokeAsync("User", User.Claims.ToList()[0].ToString())
                        }
                        else
                        {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        }

                        @if(User.IsInRole(Constants.AdminRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Orders">Панель администратора</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShopWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>